# global settings
title: "PLATEAU Workshop"
description: "Bringing together Programming Languages and Human-Computer Interaction"
url: "https://schasins.com/plateau/" # the base hostname & protocol for your site, e.g. http://example.com
year: 2025
# colocated_url: "https://2020.splashcon.org/"
# colocated_logo: "./assets/images/splash2020.png"
# colocated_title: "SPLASH2020"
logo_height: "30px"
nth_plateau: "15th"
location: "@ Harvard University, Boston MA USA"
#sublocation: "Gates & Hillman Centers, Room 6115"
workshop_date: "February 17-18, 2025"
#submission_date: "TBD"
#backup_submission_date: "Tuesday, January 10th, 2023"
#submission_site: "https://easychair.org/conferences/?conf=plateau2023"
#registration_site: "https://forms.gle/9kLW3SSa1naGnTEw6"
mailing_list_link: "https://groups.google.com/g/plateau-announcements"
#proceedings_site: "TBD"
# room_number_or_description:

organizers:
  - name: Jon Bell
    affiliation: Northeastern University
  - name: Sarah E. Chasins
    affiliation: University of California, Berkeley
  - name: Elena Glassman
    affiliation: Harvard University
  - name: Joshua Sunshine
    affiliation: Carnegie Mellon University

student_organizers:
  - name: Ian McCormack
    affiliation: Carnegie Mellon University
    
#mentors:
#  - name: Craig Anslow
#    affiliation: Victoria University of Wellington



# build settings
exclude: ["readme.md"]

sass:
  # Where you keep your scss files
  sass_dir: assets/css/

plugins:
  - jekyll-redirect-from

navbar_links:
  - title: "Home"
    url: "/"
    newtab: false
#  - title: "Registration"
#    url: "/registration"
#    newtab: false
#  - title: "Program"
#    url: "/program"
#    newtab: false
  - title: "Prior Year Sites"
    url: "/prior-year-sites"
    newtab: false
