# global settings
title: "PLATEAU Workshop"
description: "Bringing together Programming Languages and Human-Computer Interaction"
url: "https://schasins.com/plateau/" # the base hostname & protocol for your site, e.g. http://example.com
year: 2023
# colocated_url: "https://2020.splashcon.org/"
# colocated_logo: "./assets/images/splash2020.png"
# colocated_title: "SPLASH2020"
logo_height: "30px"
nth_plateau: "13th"
location: "@ Carnegie Mellon University, Pittsburgh PA USA"
sublocation: "Gates & Hillman Centers, Room 6115"
workshop_date: "February 13-14, 2023"
submission_date: "Wednesday, December 7th, 2022"
backup_submission_date: "Tuesday, January 10th, 2023"
submission_site: "https://easychair.org/conferences/?conf=plateau2023"
registration_site: "https://forms.gle/9kLW3SSa1naGnTEw6"
#proceedings_site: "TBD"
# room_number_or_description:

organizers:
  - name: Sarah E. Chasins
    affiliation: University of California, Berkeley
  - name: Elena Glassman
    affiliation: Harvard University
  - name: Joshua Sunshine
    affiliation: Carnegie Mellon University

student_organizers:
  - name: Priyan Vaithilingam
    affiliation: Harvard University
  - name: Tyler Holloway
    affiliation: Harvard University
  - name: Justin Lubin
    affiliation: University of California, Berkeley
  - name: Ian McCormack
    affiliation: Carnegie Mellon University
    
mentors:
  - name: Craig Anslow
    affiliation: Victoria University of Wellington
  - name: Titus Barik 
    affiliation: Apple
  - name: Michael Coblenz
    affiliation: University of California, San Diego
  - name: Mark Guzdial
    affiliation: University of Michigan
  - name: Nadia Polikarpova
    affiliation: University of California, San Diego
  - name: Andreas Stefik
    affiliation: University of Nevada, Las Vegas
  - name: Brian Hempel
    affiliation: UCSD
  - name: Brittany Johnson-Matthews
    affiliation: George Mason University
  - name: Emma Söderberg
    affiliation: Lund University
  - name: Will Crichton
    affiliation: Brown University
  - name: Shriram Krishnamurthi
    affiliation: Brown University
  - name: Tianyi Zhang
    affiliation: Purdue University
  - name: Felienne Hermans
    affiliation: Leiden University
  - name: Chris Martens
    affiliation: Northeastern University


# build settings
exclude: ["readme.md"]

sass:
  # Where you keep your scss files
  sass_dir: assets/css/

plugins:
  - jekyll-redirect-from

navbar_links:
  - title: "Home"
    url: "/"
    newtab: false
  - title: "Registration"
    url: "/registration"
    newtab: false
  - title: "Program"
    url: "/program"
    newtab: false
  - title: "Prior Year Sites"
    url: "/prior-year-sites"
    newtab: false
